export * from "./About";
export * from "./Contact";
export * from "./Home";
export * from "./Services";
export * from "./Staff";
export * from "./Attendance";
export * from "./Record"
export * from "./Toggle"
export * from "./PDFReport"
